[context.production.environment]
  # THESE WILL OVERRIDE VARIABLES STORED IN NETLIFY
  # UNCOMMENT AS NEEDED BY REMOVING THE # AT THE BEGINNING OF THE LINE
  # 
  # VITE_NAME = ""
  # VITE_HANDLE = ""
  # VITE_TITLE = ""
  # VITE_PROFILE_PIC = ""
  # VITE_COLOR = "" # OPTIONS: slate, gray, zinc, neutral, stone, red, orange, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose
  # VITE_ROUNDSTYLE = "" # OPTIONS: rounded, square, square-rounded
  # VITE_SMALL_LINKS_ORDER = "" # LINK TYPE SEPARATED BY COMMA. Ex: twitter,instagram,youtube
  # VITE_LARGE_LINKS_ORDER = "" # LINK TYPE SEPARATED BY COMMA. Ex: twitter,instagram,youtube
  # VITE_BITBUCKET_LINK_LARGE = ""
  # VITE_BLOGGER_LINK_LARGE = ""
  # VITE_CASHAPP_LINK_LARGE = ""
  # VITE_CODEPEN_LINK_LARGE = ""
  # VITE_CODESANDBOX_LINK_LARGE = ""
  # VITE_COINBASE_LINK_LARGE = ""
  # VITE_DISCORD_LINK_LARGE = ""
  # VITE_DRIBBBLE_LINK_LARGE = ""
  # VITE_FACEBOOK_LINK_LARGE = ""
  # VITE_GITHUB_LINK_LARGE = ""
  # VITE_GUMROAD_LINK_LARGE = ""
  # VITE_INSTAGRAM_LINK_LARGE = ""
  # VITE_INTERCOM_LINK_LARGE = ""
  # VITE_LINKEDIN_LINK_LARGE = ""
  # VITE_MASTODON_LINK_LARGE = ""
  # VITE_MEDIUM_LINK_LARGE = ""
  # VITE_MESSENGER_LINK_LARGE = ""
  # VITE_NOTION_LINK_LARGE = ""
  # VITE_ONEDRIVE_LINK_LARGE = ""
  # VITE_ONLYFANS_LINK_LARGE = ""
  # VITE_PATREON_LINK_LARGE = ""
  # VITE_PAYPAL_LINK_LARGE = ""
  # VITE_PINTEREST_LINK_LARGE = ""
  # VITE_REDDIT_LINK_LARGE = ""
  # VITE_SKYPE_LINK_LARGE = ""
  # VITE_SLACK_LINK_LARGE = ""
  # VITE_SNAPCHAT_LINK_LARGE = ""
  # VITE_SPOTIFY_LINK_LARGE = ""
  # VITE_STEAM_LINK_LARGE = ""
  # VITE_TELEGRAM_LINK_LARGE = ""
  # VITE_TIKTOK_LINK_LARGE = ""
  # VITE_TINDER_LINK_LARGE = ""
  # VITE_TWITCH_LINK_LARGE = ""
  # VITE_TWITTER_LINK_LARGE = ""
  # VITE_UPWORK_LINK_LARGE = ""
  # VITE_WHATSAPP_LINK_LARGE = ""
  # VITE_YOUTUBE_LINK_LARGE = ""
  # VITE_CALENDAR_LINK_LARGE = ""
  # VITE_MAIL_LINK_LARGE = ""
  # VITE_WEB_LINK_LARGE = ""
  # VITE_BITBUCKET_LINK_SMALL = ""
  # VITE_BLOGGER_LINK_SMALL = ""
  # VITE_CASHAPP_LINK_SMALL = ""
  # VITE_CODEPEN_LINK_SMALL = ""
  # VITE_CODESANDBOX_LINK_SMALL = ""
  # VITE_COINBASE_LINK_SMALL = ""
  # VITE_DISCORD_LINK_SMALL = ""
  # VITE_DRIBBBLE_LINK_SMALL = ""
  # VITE_FACEBOOK_LINK_SMALL = ""
  # VITE_GITHUB_LINK_SMALL = ""
  # VITE_GUMROAD_LINK_SMALL = ""
  # VITE_INSTAGRAM_LINK_SMALL = ""
  # VITE_INTERCOM_LINK_SMALL = ""
  # VITE_LINKEDIN_LINK_SMALL = ""
  # VITE_MASTODON_LINK_SMALL = ""
  # VITE_MEDIUM_LINK_SMALL = ""
  # VITE_MESSENGER_LINK_SMALL = ""
  # VITE_NOTION_LINK_SMALL = ""
  # VITE_ONEDRIVE_LINK_SMALL = ""
  # VITE_ONLYFANS_LINK_SMALL = ""
  # VITE_PATREON_LINK_SMALL = ""
  # VITE_PAYPAL_LINK_SMALL = ""
  # VITE_PINTEREST_LINK_SMALL = ""
  # VITE_REDDIT_LINK_SMALL = ""
  # VITE_SKYPE_LINK_SMALL = ""
  # VITE_SLACK_LINK_SMALL = ""
  # VITE_SNAPCHAT_LINK_SMALL = ""
  # VITE_SPOTIFY_LINK_SMALL = ""
  # VITE_STEAM_LINK_SMALL = ""
  # VITE_TELEGRAM_LINK_SMALL = ""
  # VITE_TIKTOK_LINK_SMALL = ""
  # VITE_TINDER_LINK_SMALL = ""
  # VITE_TWITCH_LINK_SMALL = ""
  # VITE_TWITTER_LINK_SMALL = ""
  # VITE_UPWORK_LINK_SMALL = ""
  # VITE_WHATSAPP_LINK_SMALL = ""
  # VITE_YOUTUBE_LINK_SMALL = ""
  # VITE_CALENDAR_LINK_SMALL = ""
  # VITE_MAIL_LINK_SMALL = ""
  # VITE_WEB_LINK_SMALL = ""